### ISSUE TITLE
React Fundamentals: Rendering Arrays "Bug" that could cause confusion

### ISSUE THREAD

**Issue by denno020** [kentcdodds/react-fundamentals#127]
I was just playing around with the Rendering Array's exercise in React Fundamentals, and I noticed that after adding the `key` prop into my solution, the exercise dashboard didn't quite reload properly, and I was able to get into a state where the list of items had 2 apples!

I assume it has something to do with comparing objects, and it's probably a concession that was made so the exercise code was as simple as possible, but thought I would bring it to your attention anyway.

Steps to reproduce:

1. Open the Rendering Arrays solution in Chrome
2. Open the `07.js` file in IDE
3. Remove the Grape item from the exercise dashboard in Chrome
4. Add a `key` prop to the `li` element in `07.js` in your IDE
5. Click on `add item` in the exercise dashboard in Chrome

Hopefully the `apple` item gets added to the list, which would then result in a list with:

- apple
- orange
- pear
- apple

And the Add Item button being disabled, so we're not able to get the Grape back. Adding and removing items gets super funky after that.

Again, this is probably a tradeoff that was decided upon to keep code as simple as possible, but I still think it could be the cause of confusion for some people.

**Comment by kentcdodds** [comment]
Hi @denno020,

This is happening due to react-script's Hot Module Replacement setup with Webpack. When the module is replaced, the items that were in memory still are, but the `allItems` are created brand new.

So rather than comparing items directly, I can compare the `id` of the item. I've fixed this. Thanks!

@all-contributors please add @denno020 for bugs
