### ISSUE TITLE
How to run tests on docker?

### ISSUE THREAD

**Issue by arjitgupta2211** [kentcdodds/react-fundamentals#167]
I am running the workshop on a docker container. To run the tests, I run the npm test command inside the container, but it gives the following error.
![Screenshot from 2021-03-24 09-46-36](https://user-images.githubusercontent.com/78952494/112289266-0f971d00-8c86-11eb-9ce4-2b6c3490a724.png)

**Comment by kentcdodds** [comment]
When you execute the test suite, run with the flag `--watchAll` (for example: `npm test -- --watchAll`). I'm not sure why, but it appears that jest can't find the `.git` directory when within a docker container.

Sorry, the docker container is only there if you can't get things working like you would normally develop a regular project on your machine. It's not recommended otherwise. Good luck!
