### ISSUE TITLE
"Wrong" information on workshop pages System Requirements

### ISSUE THREAD

**Issue by SimonEsser** [kentcdodds/react-fundamentals#256]
Hello everybody.

I am currently starting to do this course.
On the [Workshops](https://epicreact.dev/modules/react-fundamentals/react-fundamentals-welcome) side for the project setup it says that you have to run Node 10 or greater.
I am currently running Node 17 in my system. I had to downgrade to Node 16 to make it run.
Although it says "Node 10 || 11 || 12 || 13 || 14 || 15 || 16" in the README.md, it might be an idea to update the workshop page to make it more easy to see that.

On top of that I have an additional question: Will the project be updated to setup and run on Node 17 or should it maybe already run on this version or is this not planned? :)

Best Regards,
Simon

**Comment by kentcdodds** [comment]
Hello @SimonEsser! 👋

Unfortunately the project does not support Node 17 because that's a non-LTS version of Node and the tools we use in this project break with that version. If you could submit feedback via the website (there's a feedback button at the top of the page) on the page you see any issues, the Epic React team can give it a look. I only control the repos and this repo shows the correct versions.

Thanks!

**Comment by SimonEsser** [comment]
Ah of course. I will do so later on. And thanks for your quick reply @kentcdodds :)
