### ISSUE TITLE
"Sorry... nothing here." on exercise 1 and 2

### ISSUE THREAD

**Issue by Nexizz8** [kentcdodds/react-fundamentals#348]
Hi, I couldn't find the answer to my problem in any of the reported issues so that's why I have decided to create an issue myself.

Basically exercise 1 and 2 loads a not found page:

![image](https://github.com/kentcdodds/react-fundamentals/assets/32540500/2af8cc7a-84d9-45ae-9041-2b2eae0220f1)

Same for the final result:

![image](https://github.com/kentcdodds/react-fundamentals/assets/32540500/3cfd08f7-6943-43ca-b54f-d9355615fdbf)

But for some reason exercises 3 and beyond load just fine.

Seems like the routing doesn't work or something. Tried removing the repo and retrying the setup + doing `npm install` but unfortunately nothing works. Another thing I found weird was that the setup didn't ask me for my email, don't know why that would be causing the issue but just reporting it. 

Any idea how to fix this?

**Comment by Nexizz8** [comment]
Btw all the files are there so that also isn't the issue

**Comment by Nexizz8** [comment]
Hmm, odd @kentcdodds. I find it so weird because i even tried your exact steps after entirely removing the local repo but it still results in the same issue. A colleague of mine tested it out on his laptop because he also has a license and he didn't run into any issues as well. Could it have to do with the current versions of node, npm or git that i have installed? They are higher then the versions you require in the course:

NodeJs version:  `v16.17.1`
npm version: `9.7.1`
git version: `2.37.1.windows.1`

![image](https://github.com/kentcdodds/react-fundamentals/assets/32540500/b78ce56d-700c-466f-8343-c459e6d73e52)

Other than that I can't think of a reason what's causing this...

**Comment by kentcdodds** [comment]
Yeah, that's very odd. I'm sorry it's not working for you :( Do you see any errors in the terminal or browser console?

**Comment by Nexizz8** [comment]
Yeah i'm closing this issue because it does work for me with the react hooks repo and this repo also works from exercise 2 and beyond, so I think it's not worth investigating since I'm the only one with this issue.

**Comment by qaczy** [comment]
Hey, you are not the only one. I had the same issue. However the problem was with ex. 1,2,3,4. 
Git, Node and NPM were up to date. 

I solved a bit of that problem by uninstalling Node and NPM, deleted all left folders after uninstall (I'm using Win11), restarting system and installing once again Node and NPM. 
<img width="597" alt="image" src="https://github.com/kentcdodds/react-fundamentals/assets/30316338/e7a5ecc7-b7d6-4cac-acc2-d31b56978cf5">
After those steps only exercise 1 is having problem. However going to "Final" works fine, don't remember behavior of that before reinstalling. 
What's more exercise 1 is working correctly when I'm using http://localhost:3000/isolated/exercise/01.html previously it didn't.
