### ISSUE TITLE
Setup fails on validation step with jest timeout

### ISSUE THREAD

**Issue by bhumijgupta** [kentcdodds/react-fundamentals#87]
When running the setup with `npm run setup -s`, the Project Validation steps fails with jest timeout.

## Screenshot
![image](https://user-images.githubusercontent.com/30751793/95177050-575ee080-07db-11eb-88c0-7fe08368d1b5.png)

**Comment by kentcdodds** [comment]
Looks like the tests are taking an exceedingly long time to run on your machine for some reason. That's not normal. What version of node are you running? What operating system are you on?

I'm also putting together a troubleshooting guide, maybe this will help? https://docs.google.com/document/d/1OUYIaGsIGRpmaVuuaGKKhh-toHu_R4L-lMjjXbgerkE/edit#

**Comment by bhumijgupta** [comment]
I am using -
Operating System: Ubuntu 18.04
NodeJS: v12.8.4

**Comment by kentcdodds** [comment]
That is very strange. I'm not sure what could be causing the tests to run so slowly for you. Luckily the tests aren't required for most of the workshops and you can also use codesandbox for the workshops where tests are required. I'm afraid there's not much more I can do because it seems like a problem with your machine 😬

**Comment by bhumijgupta** [comment]
Thank you for the response!
